### ISSUE TITLE
Product shipping from multiple warehouses

### ISSUE THREAD

**Issue by george-haeger** [Sitecore/Sitecore.Commerce.Headstart.ReactAdmin#127]
We often talk about the fact that products can be shipped from multiple locations but really dont have a way to show how this would look like on the product details page. We would like to have the ability on the product details page to show that product can sit in multiple warehouses. We do not need to do much more than that for the demos. We can show explain that they can manage this in their middle ware. We really need to show that multiple warehouses is a thing and that they have options.

**Comment by abishop451** [comment]
As an Admin User, when I create or edit a product, I want to (multi) select the locations that this product can fulfill from, and optionally set the inventory for each location as well. 

1. Remove the Inventory section on the Product Details page
2. Change the Shipping section on the Product Details page to read "Shipping & Inventory"
3. Within the Shipping & Inventory section, add a toggle for "This product fulfills from one location" & "This product fulfills from multiple locations"
4. If "This product fulfills from one location" is selected, show the Ship From Company and Ship From Address selectors.  This selection will set `Product.ShipFromAddressID`  
5. If "This product fulfills from multiple locations" is selected, show a dropdown to select the address for the product, as well as a Quantity Available property.  This is creating an Inventory Record for the product.  Allow user to continue adding more addresses & quantity.


Discussion needed about how to handle the Product.Inventory property. 
- `Product.Inventory.Enabled` must be `true` when using inventory records
- `Product.Inventory.QuantityAvailable` will be the sum of all Inventory Records if they are being used

Variant Level Inventory and Ship-from locations will need to be revisited as well.

Here is some inspiration from Affinity designs
![image](https://github.com/Sitecore/Sitecore.Commerce.Headstart.ReactAdmin/assets/11871752/f61b4798-c676-4836-a6ff-b89239240716)
