### ISSUE TITLE
500 Errors: Canary deployemnt on certain pages

### ISSUE THREAD

**Issue by robertsoniv** [Sitecore/Sitecore.Commerce.Headstart.ReactAdmin#138]
/products
/orders
/returns
/settings

All result in the following error view:
![image](https://github.com/Sitecore/Sitecore.Commerce.Headstart.ReactAdmin/assets/4377246/7287dd05-d72a-468d-901c-3d24c6bebe6c)

**Comment by crhistianramirez** [comment]
I think this is related to a vercel outage https://www.vercel-status.com/

Someone noticed the same error on a sitecoredemo app https://sitecorechat.slack.com/archives/CASEB5M38/p1686683421706819

**Comment by crhistianramirez** [comment]
This was a transient issue related to an AWS outage. No fix needed
