### ISSUE TITLE
Update experience for Product Details > Facets

### ISSUE THREAD

**Issue by abishop451** [Sitecore/Sitecore.Commerce.Headstart.ReactAdmin#147]
As an Admin User, when I create or edit a Product, I want to select the Facets that apply to this product, and then select the Facet Options that apply. 

1. On the Product Details > Facet tab, by default, do not show any facets.  Instead show a button or action that says "Add facet", along with an icon that says "This Product has no Facets". 
2. When a user selects "Add Facet", show the list of facets that had been previously defined in Settings.  
3. Once a Facet is added, show all of the Facet options and allow the user to select the options that apply to this product
4. Save the Facet and Facet Option selections, and display them on the Facet tab screen
5. Allow the user to select more than one Facet to add to the product
6. Allow the user to edit the Facet Options
7. Allow the user to Delete a Facet from a product.

Open to ideas, but possibly Step 2 above the Admin User can select all Facets at once, and then select Options after?  I'm open to seeing if setting up one facet at a time or setting up multiple facets is a better experience.

**Comment by crhistianramirez** [comment]
Complete
