### ISSUE TITLE
Supplier Detail View

### ISSUE THREAD

**Issue by abishop451** [Sitecore/Sitecore.Commerce.Headstart.ReactAdmin#163]
Let's reuse the existing layout of Buyers for the Supplier Detail view. 

1. As an MPO, when I click on a Supplier from the list page, show the the details for that Supplier, including buttons that go to Supplier Groups, Supplier Users, Supplier Catalogs, and Supplier Address
2. As an MPO, on the Supplier Detail page, show a Supplier selector so I can change between suppliers easier 
3. As a Supplier, I will not see the Supplier selector when viewing my Supplier detail page, I will only see my Supplier info
4. As an MPO or Supplier User, when I click on the buttons for Groups, Users, Catalogs, or Addresses, the header for my Supplier stays present, and the list generates below with the selected records. This make is clear what Supplier I'm viewing information for.

![image](https://github.com/Sitecore/Sitecore.Commerce.Headstart.ReactAdmin/assets/11871752/79005a0e-e710-40cb-856d-7782e1dd9bb8)

**Comment by crhistianramirez** [comment]
Merged into development
