### ISSUE TITLE
Bug: Buyer Catalog List shows inaccurate catalog-buyer assignments

### ISSUE THREAD

**Issue by abishop451** [Sitecore/Sitecore.Commerce.Headstart.ReactAdmin#175]
When viewing a Buyer Detail page, there are buttons present that allow you to click into Buyer User, Groups, or Catalogs.  The Catalogs button brings you to an innaccurate list of catalogs for the Buyer. 

For example, `Ashley-Buyer` shows that there is 1 catalog tied to this Buyer, however when I click to see the 1 catalog, a list of all catalogs show up.  I would expect to see just the 1 catalog `Ashley-Buyer`

**Comment by crhistianramirez** [comment]
This has been merged into development and is complete
