### ISSUE TITLE
Navigate to Categories from Catalog Detail page

### ISSUE THREAD

**Issue by abishop451** [Sitecore/Sitecore.Commerce.Headstart.ReactAdmin#188]
When viewing a Catalog detail page, a user should be able to view the categories for the catalog, or at minimum be able to easily navigate to them without having to go to the Catalog List page.  The only way for me to access Categories right now is to click the "Categories" button on a Catalog listing page. 

![image](https://github.com/Sitecore/Sitecore.Commerce.Headstart.ReactAdmin/assets/11871752/d53ceeba-84f3-4fc4-90c3-3b2e7690fffd)

I'd like to navigate to categories from this page:
![image](https://github.com/Sitecore/Sitecore.Commerce.Headstart.ReactAdmin/assets/11871752/59d2f37a-9e94-4d53-808e-5e00e0bd6580)

Also remove the Under Construction messaging.

**Comment by crhistianramirez** [comment]
This has been merged into development and is complete
