### ISSUE TITLE
https://sitecore-commerce-headstart-react-admin.vercel.app/manifest.json 404 status

### ISSUE THREAD

**Issue by dannya** [Sitecore/Sitecore.Commerce.Headstart.ReactAdmin#209]
At the public demo site https://sitecore-commerce-headstart-react-admin.vercel.app/ , in the HTML code of the login page, in the `<head>` there is a reference to a `manifest.json` file.

![image](https://github.com/Sitecore/Sitecore.Commerce.Headstart.ReactAdmin/assets/394687/82600dd4-ff71-444c-bfd8-d384adf1e52d)

However, this file is not resolved (404), which causes console errors and also problems parsing this non-existent manifest file:

![image](https://github.com/Sitecore/Sitecore.Commerce.Headstart.ReactAdmin/assets/394687/3faa61c8-8137-4c42-b62a-61dd2e3736d3)

**Comment by crhistianramirez** [comment]
Thanks for reporting this bug, we will have it removed shortly
