### ISSUE TITLE
Create a minimal seeding yaml file

### ISSUE THREAD

**Issue by crhistianramirez** [Sitecore/Sitecore.Commerce.Headstart.ReactAdmin#227]
We have an existing seeding file that is built against the playshop dataset and is good for exploring the API but it would be useful to have one that populates an almost blank marketplace but with some of the essentials configured (API Clients, Security Profiles, etc.) 

This could be useful for both sales working on a new demo, as well as partners

**Comment by medkrimi** [comment]
[Here](https://github.com/medkrimi/ordercloud-seed/blob/main/seeds/minimal-empty-ordercloud-seed.yml)'s one that I created for one of my customers. Has nothing except: 
- API Clients
- Security Profiles
- Admin User 
- Buyer 

Has to be reviewed, and fix the naming convention later.
