### ISSUE TITLE
Build functionality for Product Detail > Customization

### ISSUE THREAD

**Issue by crhistianramirez** [Sitecore/Sitecore.Commerce.Headstart.ReactAdmin#89]
This tab should include the product xp functionality. We'll want to update the component to make sure it is tightly integrated with react-hook-form so that reseting the form form will automatically work in the UI

Please try to follow the patterns established in the product detail component, this is a general guide for doing that:
1. Copy one of the [form folders](https://github.com/Sitecore/Sitecore.Commerce.Headstart.ReactAdmin/tree/list-view-update/src/components/products/detail/forms) to use as a template. Description form is a good one because there is only one field
2. Fill out all of the files and create your form component
3. Update [forms/meta.ts](https://github.com/Sitecore/Sitecore.Commerce.Headstart.ReactAdmin/blob/list-view-update/src/components/products/detail/forms/meta.ts). Make sure defaultValues, validationSchema, and tabFieldNames are updated. This rolls up all of the relevant form information which product detail then uses to initialize the form and to know when a tab is invalid
4. Update the placeholders in product detail to expose your form component. Please note that this needs to be done in two places because the product detail page can show a tabbed view  as well as a single page view (query param tabbed=false)

**Comment by robertsoniv** [comment]
@mmoebeck I'm assigning this one to you as well, it's probably one of the lower priority items but still necessary before we are able to merge to `main`. If you have any questions, feel free to ask - we technically do have a shared XP input; though, it's not very good.

**Comment by abishop451** [comment]
Please follow these changes for the Customizations tab:
1. Remove this text: "Add options like shirt text and sign verbiage to enable further product customization." This tab will be used for XP not for Specs and Spec Options
2. Add text that says: "Define custom data for your products"
3. Change the button text to say "Add Extended Properties"
4. Once clicked upon, allow the user to:  Name the property, set the property type (text, number, date...other?), and set the value for this product.

This new XP would then show up as an editable XP for all products.  It's value would be null for other products until an Admin user made changes to it (correct?)

The UX should allow the Admin user to create new XP or to modify the values for existing XP properties defined.

**Comment by crhistianramirez** [comment]
Complete
