### ISSUE TITLE
Build functionality for Product Detail > SEO

### ISSUE THREAD

**Issue by crhistianramirez** [Sitecore/Sitecore.Commerce.Headstart.ReactAdmin#90]
This tab will allow an admin user to modify seo meta tags for a product such as title or image, plan to store on product xp

You can refer to [this figma](https://www.figma.com/file/JlGhFhxM1J5QxLmXu2d3VJ/UCC%3A-Catalogs-(MVP)?node-id=315-32525&t=TPOjghL4PRlImuFT-0) as a guide for UX but feel free to change it up if there is a good reason to. Please try to follow the patterns established in the product detail component, this is a general guide for doing that:
1. Copy one of the [form folders](https://github.com/Sitecore/Sitecore.Commerce.Headstart.ReactAdmin/tree/list-view-update/src/components/products/detail/forms) to use as a template. Description form is a good one because there is only one field
2. Fill out all of the files and create your form component
3. Update [forms/meta.ts](https://github.com/Sitecore/Sitecore.Commerce.Headstart.ReactAdmin/blob/list-view-update/src/components/products/detail/forms/meta.ts). Make sure defaultValues, validationSchema, and tabFieldNames are updated. This rolls up all of the relevant form information which product detail then uses to initialize the form and to know when a tab is invalid
4. Update the placeholders in product detail to expose your form component. Please note that this needs to be done in two places because the product detail page can show a tabbed view  as well as a single page view (query param tabbed=false)

**Comment by george-haeger** [comment]
I am not sure about having this in the Seller application this is more of a content thing that should really be done in a CMS. Plus add in complexity of showing this international you are only taking in account for the one language. Lets talk about this one at our next team meeting. @robertsoniv

**Comment by robertsoniv** [comment]
For now we can talk to this as a feature that can use XP or some 3rd party content provider (like content hub one). OR just hide the SEO tab using the views feature.

**Comment by robertsoniv** [comment]
@george-haeger for the time being we are going to just hide the product SEO tab by default. If you need to speak to it you will be able to show it again using the "Views" menu.

**Comment by robertsoniv** [comment]
@mmoebeck one more for you! This one should be pretty quick, just change the default views / tabs that are visible (see the views menu code)

**Comment by robertsoniv** [comment]
DELETE IT INSTEAD @crhistianramirez

**Comment by crhistianramirez** [comment]
Complete
